### ISSUE TITLE
请问在控制台项目中如何注册IConfiguration服务

### ISSUE THREAD

**Issue by AMMK1991** [yangzhongke/Zack.AnyDBConfigProvider#1]
杨老师你好，你在TestsWeb项目里面的HomeController中注入了IConfiguration config，来读取数据库的RedisConnStr配置信息：
`string redisCS = config.GetSection("RedisConnStr").Get<string>();`
但我没看到你在任何地方注册了这个IConfiguration服务，应该是asp.net core框架自动注册的吧，那我在控制台项目里面怎么注册这个IConfiguration服务呢？

`
ServiceCollection services = new ServiceCollection();
`
services.是点不出扩展方法的，不知道实现类是什么呢，
`services.AddScoped<IConfiguration, 实现类？>();`
谢谢！

**Comment by yangzhongke** [comment]
ConfigurationBuilder configBuilder = new ConfigurationBuilder();
configBuilder.AddJsonFile(...);
IConfigurationRoot config = configBuilder.Build();
这样就拿到IConfigurationRoot 对象了

**Comment by AMMK1991** [comment]
杨老师，你说的这种方法获得的IConfigurationRoot 对象只能在Program类Main方法里面获取
`static void Main(string[] args)
        {
            ServiceCollection services = new ServiceCollection();
            services.AddScoped<ConfigTest>();

            ConfigurationBuilder configBuilder = new ConfigurationBuilder();
            string connStr = "Server=.;Database=demo1;Trusted_Connection=True;MultipleActiveResultSets=true";
            configBuilder.AddDbConfiguration(() => new SqlConnection(connStr), reloadOnChange: true, reloadInterval: TimeSpan.FromSeconds(2));
            IConfigurationRoot configRoot = configBuilder.Build();

            services.AddOptions()
                .Configure<ProgramConfig>(e=>configRoot.Bind(e))
                .Configure<Ftp>(e => configRoot.GetSection("Ftp").Bind(e))
                .Configure<Cors>(e => configRoot.GetSection("Cors").Bind(e));

            using (var sp = services.BuildServiceProvider())
            {
               string a = configRoot.GetSection("RedisConnStr").Get<string>();
                Console.WriteLine(a);
            }
        }`

但是在其他类里面（控制台程序），怎么获取IConfiguration 对象，再像你在实例程序里面用
`string redisCS = config.GetSection("RedisConnStr").Get<string>();`
来获取"RedisConnStr"配置的Value

**Comment by yangzhongke** [comment]
IConfigurationRoot就是继承自IConfiguration的呀，你把这个对象注册为IConfiguration的实现类不就行了吗

**Comment by AMMK1991** [comment]
注册一个单例，
services.AddSingleton<IConfigurationRoot>(configRoot);
然后在其他类的构造函数里面注入就可以读取了，谢谢老师

`public ConfigTest(IConfigurationRoot config)
        {
            this.config = config;
        }`

`public void Test()
        {
            string a = config.GetSection("One").Get<string>();
            Console.WriteLine(a);
        }`

杨老师，.net5视频教程托更好久了，啥时候更新啊，啥时候能讲asp.net core啊？blazor能不能也讲讲？
你的新书出版了吗，视频更新慢想看书

**Comment by yangzhongke** [comment]
暑假陪孩子，没时间录课，只能等孩子开学了，请理解。
这套课程会讲asp.net core的，但是不会讲blazor。blazor webassembly值得期待，也许能成；但是blazor server就是扯淡。
书预计2022年年初出版。
