### ISSUE TITLE
AddDbConfiguration throw exception but not dispose or close sqlconnection.

### ISSUE THREAD

**Issue by AlbertZhaoz** [yangzhongke/Zack.AnyDBConfigProvider#2]
If sqlconnectionStr is invalid, it may be necessary to close or dispose sqlconnection in AddConfiguration method.

**Comment by yangzhongke** [comment]
https://github.com/yangzhongke/Zack.AnyDBConfigProvider/blob/main/Zack.AnyDBConfigProvider/DBConfigurationProvider.cs
As I use 'using' to manange the connection, it would be closed properly.
```
using (var conn = options.CreateDbConnection())
{
    conn.Open();
    DoLoad(tableName, conn);
}
```

**Comment by AlbertZhaoz** [comment]
Thanks.
