### ISSUE TITLE
默认创建t_configs

### ISSUE THREAD

**Issue by FeiJerry** [yangzhongke/Zack.AnyDBConfigProvider#3]
杨老师，您好！既然定好了，为什么不自动创建t_configs呢？

![image](https://user-images.githubusercontent.com/48877879/171550253-6964c245-5871-4389-89c6-1b0054262957.png)

**Comment by yangzhongke** [comment]
数据我也自动给你填上吗？

**Comment by yangzhongke** [comment]
而且不同数据库的建表语句语法不一样，天下这么多数据库，我这不是给自己挖坑吗？
