### ISSUE TITLE
For DBConfigurationProvider: Load(), move  lockObj.EnterWriteLock(); into using of CreateDbConnection

### ISSUE THREAD

**Issue by w1990ww1990w** [yangzhongke/Zack.AnyDBConfigProvider#4]
Suggest move  lockObj.EnterWriteLock(); into using of CreateDbConnection  for DBConfigurationProvider: Load(). It may cause deadlock if CreateDbConnection  will use same resource. Correct me if there is any side effect with thanks.

**Comment by yangzhongke** [comment]
Thanks for your advice.
Typically, the implementation of CreateDbConnection  is creating DbConnection object, could you please figure out when there would be other codes other than  creating DbConnection?
